Gray

diff --git a/.github/workflows/main (Build IOS).yml b/.github/workflows/main (Build IOS).yml
--- a/.github/workflows/main (Build IOS).yml
+++ b/.github/workflows/main (Build IOS).yml
@@ -39,6 +39,11 @@ jobs:
       ###########################
       - if: matrix.targetPlatform == 'Android'
         uses: jlumbroso/free-disk-space@v1.3.1
+
+      - name: Clean build dirs before Unity build
+        run: |
+          rm -rf build/iOS || true
+          rm -rf build/iOS/iOS || true
       
       ###########################
       #          Build          #
@@ -50,7 +55,19 @@ jobs:
           UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
         with:
           targetPlatform: ${{ matrix.targetPlatform }}
-      
+
+      - name: Поиск NotificationService.swift в pbxproj
+        run: grep NotificationService.swift build/iOS/iOS/Unity-iPhone.xcodeproj/project.pbxproj || true
+
+      - name: Universal NotificationService.swift search
+        run: find build -name "NotificationService.swift" -print
+
+      - name: Проверка NotificationService.swift presence
+        if: matrix.targetPlatform == 'iOS'
+        run: |
+          find build
+          test -f build/iOS/iOS/notifications/NotificationService.swift || (echo "❌ NotificationService.swift missing!" && exit 1)
+
       ###########################
       #          Upload         #
       ###########################
@@ -84,12 +101,26 @@ jobs:
           name: Build-${{ matrix.targetPlatform }}
           path: build/${{ matrix.targetPlatform }}
 
+      - name: Проверка NotificationService.swift на Mac
+        run: |
+          find build
+          test -f build/iOS/iOS/notifications/NotificationService.swift || (echo "❌ NotificationService.swift missing on mac!" && exit 1)
+          grep NotificationService.swift build/iOS/iOS/Unity-iPhone.xcodeproj/project.pbxproj || true
+
+
       ###################
       #  xcode-version  #
       ###################
       - uses: maxim-lobanov/setup-xcode@v1
         with:
           xcode-version: '16.3.0'
+
+      - name: Список Xcode targets
+        run: |
+          ruby -e "require 'xcodeproj'; p Xcodeproj::Project.open('build/iOS/iOS/Unity-iPhone.xcodeproj').targets.map(&:name)"
+
+      - name: Patch Embed App Extension
+        run: ruby fastlane/patch_embed_extension.rb build/iOS/iOS/Unity-iPhone.xcodeproj Unity-iPhone notifications
 
       ###########################################
       #  Fix File Permissions and Run fastlane  #
@@ -121,6 +152,12 @@ jobs:
           #bundle exec fastlane ios release
           bundle exec fastlane ios beta
           #bundle exec fastlane ios build
+
+      - name: Upload IPA
+        uses: actions/upload-artifact@v4
+        with:
+          name: ios-ipa
+          path: build/iOS/ipa_out/*.ipa
 
       ####################################
       #  Cleanup to avoid storage limit  #
